name: Lint

on: push

jobs:
  run-linter:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install modules
        run: npm install
      
      - name: Run ESLint
        run: npm run lint
